import type { ToolSeed } from "./types";

export const toolSeeds: ToolSeed[] = [
  {
    "slug": "background-remover",
    "title": "Background Remover",
    "category": "image",
    "shortDescription": "Remove image backgrounds online in seconds.",
    "processorKey": "imageBgRemover",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [
      "ai-assisted",
      "privacy-safe"
    ],
    "featured": true,
    "icon": "image"
  },
  {
    "slug": "image-upscaler",
    "title": "Image Upscaler",
    "category": "image",
    "shortDescription": "Increase image size while keeping details crisp.",
    "processorKey": "imageUpscale",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [
      "premium",
      "batch-ready"
    ],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "image-compressor",
    "title": "Image Compressor",
    "category": "image",
    "shortDescription": "Shrink image file size without obvious quality loss.",
    "processorKey": "imageCompress",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "image-resizer",
    "title": "Image Resizer",
    "category": "image",
    "shortDescription": "Resize images to exact dimensions instantly.",
    "processorKey": "imageResize",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "image-cropper",
    "title": "Image Cropper",
    "category": "image",
    "shortDescription": "Crop an image to a custom frame or aspect ratio.",
    "processorKey": "imageCrop",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "image-converter",
    "title": "Image Converter",
    "category": "image",
    "shortDescription": "Convert between popular image formats online.",
    "processorKey": "imageConvert",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "blur-background",
    "title": "Blur Background",
    "category": "image",
    "shortDescription": "Create a soft blurred background effect.",
    "processorKey": "imageBlur",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "sharpen-image",
    "title": "Sharpen Image",
    "category": "image",
    "shortDescription": "Improve edge clarity and visual detail.",
    "processorKey": "imageSharpen",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "rotate-image",
    "title": "Rotate Image",
    "category": "image",
    "shortDescription": "Rotate an image clockwise or counterclockwise.",
    "processorKey": "imageRotate",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "flip-image",
    "title": "Flip Image",
    "category": "image",
    "shortDescription": "Flip an image horizontally or vertically.",
    "processorKey": "imageFlip",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "color-picker",
    "title": "Color Picker",
    "category": "image",
    "shortDescription": "Pick and copy color values from any image.",
    "processorKey": "colorPicker",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "meme-generator",
    "title": "Meme Generator",
    "category": "image",
    "shortDescription": "Make fast, shareable meme images.",
    "processorKey": "memeGenerator",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "screenshot-to-text",
    "title": "Screenshot to Text",
    "category": "image",
    "shortDescription": "Extract text from a screenshot and clean it up.",
    "processorKey": "ocrAssist",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "image-to-pdf",
    "title": "Image to PDF",
    "category": "image",
    "shortDescription": "Turn images into a neat PDF in one step.",
    "processorKey": "imageToPdf",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "pdf-to-image",
    "title": "PDF to Image",
    "category": "image",
    "shortDescription": "Export PDF pages as images.",
    "processorKey": "pdfToImage",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "face-blur",
    "title": "Face Blur",
    "category": "image",
    "shortDescription": "Blur faces for privacy-safe sharing.",
    "processorKey": "faceBlur",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "object-removal",
    "title": "Object Removal",
    "category": "image",
    "shortDescription": "Remove small objects from photos with a guided workflow.",
    "processorKey": "objectRemoval",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [
      "ai-assisted"
    ],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "photo-editor",
    "title": "Photo Editor",
    "category": "image",
    "shortDescription": "Make quick edits, tweaks, and exports in the browser.",
    "processorKey": "imageEditor",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "image-metadata-viewer",
    "title": "Image Metadata Viewer",
    "category": "image",
    "shortDescription": "Inspect size, type, and metadata details.",
    "processorKey": "imageMetadata",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "profile-picture-maker",
    "title": "Profile Picture Maker",
    "category": "image",
    "shortDescription": "Create polished avatar-ready profile pictures.",
    "processorKey": "avatarMaker",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "passport-photo-tool",
    "title": "Passport Photo Tool",
    "category": "image",
    "shortDescription": "Prepare passport-style photos with proper sizing.",
    "processorKey": "passportPhoto",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "transparent-png-creator",
    "title": "Transparent PNG Creator",
    "category": "image",
    "shortDescription": "Export a clean transparent PNG.",
    "processorKey": "transparentPng",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "aspect-ratio-editor",
    "title": "Aspect Ratio Editor",
    "category": "image",
    "shortDescription": "Set exact aspect ratios for any platform.",
    "processorKey": "aspectRatio",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "thumbnail-maker",
    "title": "Thumbnail Maker",
    "category": "image",
    "shortDescription": "Generate eye-catching thumbnail layouts.",
    "processorKey": "thumbnailMaker",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "sticker-maker",
    "title": "Sticker Maker",
    "category": "image",
    "shortDescription": "Turn cutouts into sticker-ready assets.",
    "processorKey": "stickerMaker",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "image"
  },
  {
    "slug": "merge-pdf",
    "title": "Merge PDF",
    "category": "pdf",
    "shortDescription": "Combine multiple PDFs into one file.",
    "processorKey": "pdfMerge",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": true,
    "icon": "pdf"
  },
  {
    "slug": "split-pdf",
    "title": "Split PDF",
    "category": "pdf",
    "shortDescription": "Split a PDF into separate files or page ranges.",
    "processorKey": "pdfSplit",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "compress-pdf",
    "title": "Compress PDF",
    "category": "pdf",
    "shortDescription": "Reduce PDF size while preserving readability.",
    "processorKey": "pdfCompress",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "unlock-pdf",
    "title": "Unlock PDF",
    "category": "pdf",
    "shortDescription": "Open a password-protected PDF when permitted.",
    "processorKey": "pdfUnlock",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "protect-pdf",
    "title": "Protect PDF",
    "category": "pdf",
    "shortDescription": "Add password protection to a PDF.",
    "processorKey": "pdfProtect",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "rotate-pdf",
    "title": "Rotate PDF",
    "category": "pdf",
    "shortDescription": "Rotate PDF pages to the correct orientation.",
    "processorKey": "pdfRotate",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "reorder-pages",
    "title": "Reorder Pages",
    "category": "pdf",
    "shortDescription": "Rearrange PDF pages with a simple drag workflow.",
    "processorKey": "pdfReorder",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "add-page-numbers",
    "title": "Add Page Numbers",
    "category": "pdf",
    "shortDescription": "Add clean page numbering to a PDF.",
    "processorKey": "pdfPageNumbers",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "watermark-pdf",
    "title": "Watermark PDF",
    "category": "pdf",
    "shortDescription": "Add a tasteful text or image watermark.",
    "processorKey": "pdfWatermark",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "remove-pages",
    "title": "Remove Pages",
    "category": "pdf",
    "shortDescription": "Delete selected pages from a PDF.",
    "processorKey": "pdfRemovePages",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "pdf-to-jpg",
    "title": "PDF to JPG",
    "category": "pdf",
    "shortDescription": "Export PDF pages as JPG images.",
    "processorKey": "pdfToJpg",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "jpg-to-pdf",
    "title": "JPG to PDF",
    "category": "pdf",
    "shortDescription": "Convert JPG images into a PDF.",
    "processorKey": "imagesToPdf",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "word-to-pdf",
    "title": "Word to PDF",
    "category": "pdf",
    "shortDescription": "Convert Word documents to PDF output.",
    "processorKey": "docToPdf",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "pdf-to-word",
    "title": "PDF to Word",
    "category": "pdf",
    "shortDescription": "Convert PDF content into an editable Word file.",
    "processorKey": "pdfToDoc",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "excel-to-pdf",
    "title": "Excel to PDF",
    "category": "pdf",
    "shortDescription": "Create a clean PDF from spreadsheet files.",
    "processorKey": "sheetToPdf",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "pdf-to-png",
    "title": "PDF to PNG",
    "category": "pdf",
    "shortDescription": "Export PDF pages as PNG images.",
    "processorKey": "pdfToPng",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "pdf-signer",
    "title": "PDF Signer",
    "category": "pdf",
    "shortDescription": "Place a signature block or draw a signature overlay.",
    "processorKey": "pdfSigner",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "pdf-annotator",
    "title": "PDF Annotator",
    "category": "pdf",
    "shortDescription": "Mark up a PDF with notes and highlights.",
    "processorKey": "pdfAnnotator",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "pdf-reader-helper",
    "title": "PDF Reader Helper",
    "category": "pdf",
    "shortDescription": "Improve reading with quick page tools and shortcuts.",
    "processorKey": "pdfReader",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "pdf-ocr-helper",
    "title": "PDF OCR Helper",
    "category": "pdf",
    "shortDescription": "Extract searchable text from scanned PDFs.",
    "processorKey": "pdfOcr",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [
      "ocr"
    ],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "pdf-metadata-viewer",
    "title": "PDF Metadata Viewer",
    "category": "pdf",
    "shortDescription": "Inspect PDF metadata and document details.",
    "processorKey": "pdfMetadata",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "pdf"
  },
  {
    "slug": "video-trimmer",
    "title": "Video Trimmer",
    "category": "video-audio",
    "shortDescription": "Trim video clips to the exact segment you need.",
    "processorKey": "videoTrim",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "video-merger",
    "title": "Video Merger",
    "category": "video-audio",
    "shortDescription": "Join multiple video files into one timeline.",
    "processorKey": "videoMerge",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "video-compressor",
    "title": "Video Compressor",
    "category": "video-audio",
    "shortDescription": "Shrink video size for easier sharing.",
    "processorKey": "videoCompress",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "video-to-mp3",
    "title": "Video to MP3",
    "category": "video-audio",
    "shortDescription": "Extract audio from video files quickly.",
    "processorKey": "videoToMp3",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": true,
    "featureFlags": [
      "media"
    ],
    "featured": true,
    "icon": "video"
  },
  {
    "slug": "mute-video",
    "title": "Mute Video",
    "category": "video-audio",
    "shortDescription": "Remove the audio track from a video file.",
    "processorKey": "muteVideo",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "change-playback-speed",
    "title": "Change Playback Speed",
    "category": "video-audio",
    "shortDescription": "Speed up or slow down a video.",
    "processorKey": "playbackSpeed",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "reverse-video",
    "title": "Reverse Video",
    "category": "video-audio",
    "shortDescription": "Create a reversed playback effect.",
    "processorKey": "reverseVideo",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "audio-compressor",
    "title": "Audio Compressor",
    "category": "video-audio",
    "shortDescription": "Reduce audio file size with light processing.",
    "processorKey": "audioCompress",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "audio-cutter",
    "title": "Audio Cutter",
    "category": "video-audio",
    "shortDescription": "Cut an audio clip to the exact range.",
    "processorKey": "audioCut",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "audio-merger",
    "title": "Audio Merger",
    "category": "video-audio",
    "shortDescription": "Merge multiple audio files into one.",
    "processorKey": "audioMerge",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "convert-video-formats",
    "title": "Convert Video Formats",
    "category": "video-audio",
    "shortDescription": "Convert between common video formats.",
    "processorKey": "videoConvert",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "convert-audio-formats",
    "title": "Convert Audio Formats",
    "category": "video-audio",
    "shortDescription": "Convert between common audio formats.",
    "processorKey": "audioConvert",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "gif-maker",
    "title": "GIF Maker",
    "category": "video-audio",
    "shortDescription": "Turn short clips into animated GIFs.",
    "processorKey": "gifMaker",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "subtitle-adder",
    "title": "Subtitle Adder",
    "category": "video-audio",
    "shortDescription": "Overlay subtitle files onto video clips.",
    "processorKey": "subtitleAdder",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "subtitle-extractor",
    "title": "Subtitle Extractor",
    "category": "video-audio",
    "shortDescription": "Extract embedded subtitles from a video.",
    "processorKey": "subtitleExtractor",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "frame-grabber",
    "title": "Frame Grabber",
    "category": "video-audio",
    "shortDescription": "Capture still frames from a video.",
    "processorKey": "frameGrabber",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "video-to-gif",
    "title": "Video to GIF",
    "category": "video-audio",
    "shortDescription": "Convert a video segment into a GIF.",
    "processorKey": "videoToGif",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "audio-normalizer",
    "title": "Audio Normalizer",
    "category": "video-audio",
    "shortDescription": "Balance audio loudness for a steadier result.",
    "processorKey": "audioNormalize",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client-heavy",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "video"
  },
  {
    "slug": "thumbnail-generator",
    "title": "Thumbnail Generator",
    "category": "social",
    "shortDescription": "Design platform-friendly thumbnails fast.",
    "processorKey": "socialThumbnail",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": true,
    "icon": "social"
  },
  {
    "slug": "caption-generator",
    "title": "Caption Generator",
    "category": "social",
    "shortDescription": "Draft captions for social posts and reels.",
    "processorKey": "socialCaption",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": true,
    "featureFlags": [
      "creator"
    ],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "hashtag-generator",
    "title": "Hashtag Generator",
    "category": "social",
    "shortDescription": "Generate relevant hashtags for your post.",
    "processorKey": "socialHashtags",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "post-scheduler-helper",
    "title": "Post Scheduler Helper",
    "category": "social",
    "shortDescription": "Plan and organize posts before publishing.",
    "processorKey": "postPlanner",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "bio-generator",
    "title": "Bio Generator",
    "category": "social",
    "shortDescription": "Write a concise profile bio in the right tone.",
    "processorKey": "socialBio",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "social-post-formatter",
    "title": "Social Post Formatter",
    "category": "social",
    "shortDescription": "Reformat text for social network readability.",
    "processorKey": "socialFormat",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "aspect-ratio-presets",
    "title": "Aspect Ratio Presets",
    "category": "social",
    "shortDescription": "Pick ratios for Instagram, YouTube, TikTok, and more.",
    "processorKey": "socialRatios",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "profile-image-resizer",
    "title": "Profile Image Resizer",
    "category": "social",
    "shortDescription": "Resize avatars for any social platform.",
    "processorKey": "profileResize",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "story-post-reel-size-converter",
    "title": "Story Post Reel Size Converter",
    "category": "social",
    "shortDescription": "Convert content dimensions across formats.",
    "processorKey": "socialSizeConvert",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "content-idea-generator",
    "title": "Content Idea Generator",
    "category": "social",
    "shortDescription": "Brainstorm fresh content ideas quickly.",
    "processorKey": "contentIdeas",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": true,
    "featureFlags": [
      "ai-assisted"
    ],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "title-generator",
    "title": "Title Generator",
    "category": "social",
    "shortDescription": "Create stronger titles for posts and videos.",
    "processorKey": "titleGenerator",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "hook-generator",
    "title": "Hook Generator",
    "category": "social",
    "shortDescription": "Draft stronger opening hooks for short-form content.",
    "processorKey": "hookGenerator",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "short-form-script-helper",
    "title": "Short Form Script Helper",
    "category": "social",
    "shortDescription": "Outline short-form video scripts with structure.",
    "processorKey": "scriptHelper",
    "inputType": "mixed",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "social"
  },
  {
    "slug": "json-formatter",
    "title": "JSON Formatter",
    "category": "dev",
    "shortDescription": "Format and beautify JSON data.",
    "processorKey": "jsonFormat",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": true,
    "icon": "dev"
  },
  {
    "slug": "json-minifier",
    "title": "JSON Minifier",
    "category": "dev",
    "shortDescription": "Minify JSON for transport or storage.",
    "processorKey": "jsonMinify",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "base64-encoder-decoder",
    "title": "Base64 Encoder / Decoder",
    "category": "dev",
    "shortDescription": "Encode or decode Base64 text instantly.",
    "processorKey": "base64Codec",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "jwt-decoder",
    "title": "JWT Decoder",
    "category": "dev",
    "shortDescription": "Decode JWT payloads for quick inspection.",
    "processorKey": "jwtDecode",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "sql-formatter",
    "title": "SQL Formatter",
    "category": "dev",
    "shortDescription": "Format SQL queries into readable blocks.",
    "processorKey": "sqlFormat",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "html-minifier",
    "title": "HTML Minifier",
    "category": "dev",
    "shortDescription": "Minify HTML for smaller payloads.",
    "processorKey": "htmlMinify",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "css-minifier",
    "title": "CSS Minifier",
    "category": "dev",
    "shortDescription": "Minify CSS with a simple workflow.",
    "processorKey": "cssMinify",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "js-minifier",
    "title": "JS Minifier",
    "category": "dev",
    "shortDescription": "Minify JavaScript text in the browser.",
    "processorKey": "jsMinify",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "url-encoder-decoder",
    "title": "URL Encoder / Decoder",
    "category": "dev",
    "shortDescription": "Encode and decode URLs cleanly.",
    "processorKey": "urlCodec",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "regex-tester",
    "title": "Regex Tester",
    "category": "dev",
    "shortDescription": "Test and validate regular expressions.",
    "processorKey": "regexTester",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "uuid-generator",
    "title": "UUID Generator",
    "category": "dev",
    "shortDescription": "Generate secure UUID values quickly.",
    "processorKey": "uuidGenerator",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "hash-generator",
    "title": "Hash Generator",
    "category": "dev",
    "shortDescription": "Create secure hash values from text.",
    "processorKey": "hashGenerator",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "timestamp-converter",
    "title": "Timestamp Converter",
    "category": "dev",
    "shortDescription": "Convert between timestamps and dates.",
    "processorKey": "timestampConverter",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "cron-generator",
    "title": "Cron Generator",
    "category": "dev",
    "shortDescription": "Build and inspect cron expressions.",
    "processorKey": "cronGenerator",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "diff-checker",
    "title": "Diff Checker",
    "category": "dev",
    "shortDescription": "Compare two text snippets and see changes.",
    "processorKey": "diffChecker",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "color-converter",
    "title": "Color Converter",
    "category": "dev",
    "shortDescription": "Convert HEX, RGB, and HSL values.",
    "processorKey": "colorConverter",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "markdown-preview",
    "title": "Markdown Preview",
    "category": "dev",
    "shortDescription": "Preview markdown output as you type.",
    "processorKey": "markdownPreview",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "yaml-formatter",
    "title": "YAML Formatter",
    "category": "dev",
    "shortDescription": "Format YAML into readable structure.",
    "processorKey": "yamlFormat",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "xml-formatter",
    "title": "XML Formatter",
    "category": "dev",
    "shortDescription": "Format XML for easier debugging.",
    "processorKey": "xmlFormat",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "escape-unescape",
    "title": "Escape / Unescape Tool",
    "category": "dev",
    "shortDescription": "Escape or unescape text for code workflows.",
    "processorKey": "escapeUnescape",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "code-snippet-formatter",
    "title": "Code Snippet Formatter",
    "category": "dev",
    "shortDescription": "Format snippets with clean spacing.",
    "processorKey": "codeSnippetFormatter",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "api-request-builder",
    "title": "API Request Builder",
    "category": "dev",
    "shortDescription": "Draft a reusable API request template.",
    "processorKey": "apiRequestBuilder",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "dev"
  },
  {
    "slug": "word-counter",
    "title": "Word Counter",
    "category": "text",
    "shortDescription": "Count words, characters, and lines fast.",
    "processorKey": "textStats",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": true,
    "icon": "text"
  },
  {
    "slug": "character-counter",
    "title": "Character Counter",
    "category": "text",
    "shortDescription": "Track character length across text content.",
    "processorKey": "textStats",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "case-converter",
    "title": "Case Converter",
    "category": "text",
    "shortDescription": "Convert text between common letter cases.",
    "processorKey": "caseConverter",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "lorem-ipsum-generator",
    "title": "Lorem Ipsum Generator",
    "category": "text",
    "shortDescription": "Generate placeholder text in different lengths.",
    "processorKey": "loremGenerator",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "line-sorter",
    "title": "Line Sorter",
    "category": "text",
    "shortDescription": "Sort lines alphabetically or numerically.",
    "processorKey": "lineSorter",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "duplicate-line-remover",
    "title": "Duplicate Line Remover",
    "category": "text",
    "shortDescription": "Clean duplicate lines from pasted text.",
    "processorKey": "duplicateLines",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "sentence-splitter",
    "title": "Sentence Splitter",
    "category": "text",
    "shortDescription": "Split text into individual sentences.",
    "processorKey": "sentenceSplitter",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "paragraph-rewriter-helper",
    "title": "Paragraph Rewriter Helper",
    "category": "text",
    "shortDescription": "Rewrite paragraphs into a clearer draft.",
    "processorKey": "paragraphRewriter",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "reading-time-calculator",
    "title": "Reading Time Calculator",
    "category": "text",
    "shortDescription": "Estimate how long a text will take to read.",
    "processorKey": "readingTime",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "text-cleaner",
    "title": "Text Cleaner",
    "category": "text",
    "shortDescription": "Remove extra spacing and noisy characters.",
    "processorKey": "textCleaner",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "slug-generator",
    "title": "Slug Generator",
    "category": "text",
    "shortDescription": "Turn titles into URL-friendly slugs.",
    "processorKey": "slugGenerator",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "title-case-converter",
    "title": "Title Case Converter",
    "category": "text",
    "shortDescription": "Convert strings into title case.",
    "processorKey": "titleCase",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "text-compare",
    "title": "Text Compare",
    "category": "text",
    "shortDescription": "Compare two blocks of text side by side.",
    "processorKey": "textCompare",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "random-text-generator",
    "title": "Random Text Generator",
    "category": "text",
    "shortDescription": "Generate randomized sample text.",
    "processorKey": "randomText",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "translator-helper",
    "title": "Translator Helper",
    "category": "text",
    "shortDescription": "Prepare text for translation workflows.",
    "processorKey": "translatorAssist",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "text-summarizer-helper",
    "title": "Text Summarizer Helper",
    "category": "text",
    "shortDescription": "Condense long text into a shorter draft.",
    "processorKey": "summarizerAssist",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "keyword-extractor",
    "title": "Keyword Extractor",
    "category": "text",
    "shortDescription": "Highlight likely keywords from pasted content.",
    "processorKey": "keywordExtractor",
    "inputType": "text",
    "outputType": "text",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "text"
  },
  {
    "slug": "currency-converter",
    "title": "Currency Converter",
    "category": "unit-money",
    "shortDescription": "Convert between currencies with a clean interface.",
    "processorKey": "currencyConverter",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": true,
    "icon": "unit"
  },
  {
    "slug": "length-converter",
    "title": "Length Converter",
    "category": "unit-money",
    "shortDescription": "Convert length units online.",
    "processorKey": "unitConverter",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "weight-converter",
    "title": "Weight Converter",
    "category": "unit-money",
    "shortDescription": "Convert weight units online.",
    "processorKey": "unitConverter",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "temperature-converter",
    "title": "Temperature Converter",
    "category": "unit-money",
    "shortDescription": "Convert Celsius, Fahrenheit, and Kelvin.",
    "processorKey": "unitConverter",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "speed-converter",
    "title": "Speed Converter",
    "category": "unit-money",
    "shortDescription": "Convert speed units like km/h and mph.",
    "processorKey": "unitConverter",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "area-converter",
    "title": "Area Converter",
    "category": "unit-money",
    "shortDescription": "Convert area units with accuracy.",
    "processorKey": "unitConverter",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "percentage-calculator",
    "title": "Percentage Calculator",
    "category": "unit-money",
    "shortDescription": "Calculate percentages quickly.",
    "processorKey": "percentageCalculator",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "bmi-calculator",
    "title": "BMI Calculator",
    "category": "unit-money",
    "shortDescription": "Calculate body mass index from height and weight.",
    "processorKey": "bmiCalculator",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "tip-calculator",
    "title": "Tip Calculator",
    "category": "unit-money",
    "shortDescription": "Work out a tip and split totals.",
    "processorKey": "tipCalculator",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "loan-calculator",
    "title": "Loan Calculator",
    "category": "unit-money",
    "shortDescription": "Estimate monthly loan payments.",
    "processorKey": "loanCalculator",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "tax-calculator",
    "title": "Tax Calculator",
    "category": "unit-money",
    "shortDescription": "Estimate tax amounts from a base number.",
    "processorKey": "taxCalculator",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "discount-calculator",
    "title": "Discount Calculator",
    "category": "unit-money",
    "shortDescription": "Calculate sale price and savings.",
    "processorKey": "discountCalculator",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "basic-math-calculator",
    "title": "Basic Math Calculator",
    "category": "unit-money",
    "shortDescription": "Use a simple online calculator.",
    "processorKey": "basicMathCalculator",
    "inputType": "text",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "date-calculator",
    "title": "Date Calculator",
    "category": "unit-money",
    "shortDescription": "Add or subtract dates and days.",
    "processorKey": "dateCalculator",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "age-calculator",
    "title": "Age Calculator",
    "category": "unit-money",
    "shortDescription": "Calculate age from a birth date.",
    "processorKey": "ageCalculator",
    "inputType": "number",
    "outputType": "result",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "unit"
  },
  {
    "slug": "file-converter",
    "title": "File Converter",
    "category": "file",
    "shortDescription": "Convert between supported file types.",
    "processorKey": "fileConverter",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [
      "batch-ready"
    ],
    "featured": false,
    "icon": "file"
  },
  {
    "slug": "archive-helper",
    "title": "Archive Helper",
    "category": "file",
    "shortDescription": "Create or unpack common archive formats.",
    "processorKey": "archiveHelper",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": true,
    "featureFlags": [],
    "featured": false,
    "icon": "file"
  },
  {
    "slug": "split-files",
    "title": "Split Files",
    "category": "file",
    "shortDescription": "Split large files into smaller parts.",
    "processorKey": "splitFiles",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "file"
  },
  {
    "slug": "combine-files",
    "title": "Combine Files",
    "category": "file",
    "shortDescription": "Join multiple files into one export.",
    "processorKey": "combineFiles",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "file"
  },
  {
    "slug": "file-renamer",
    "title": "File Renamer",
    "category": "file",
    "shortDescription": "Rename batches of files with a safer workflow.",
    "processorKey": "fileRenamer",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "file"
  },
  {
    "slug": "folder-organizer-helper",
    "title": "Folder Organizer Helper",
    "category": "file",
    "shortDescription": "Plan a folder cleanup and organization pass.",
    "processorKey": "folderOrganizer",
    "inputType": "mixed",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "file"
  },
  {
    "slug": "checksum-tool",
    "title": "Checksum Tool",
    "category": "file",
    "shortDescription": "Generate hashes to verify file integrity.",
    "processorKey": "checksumTool",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "file"
  },
  {
    "slug": "duplicate-finder-helper",
    "title": "Duplicate Finder Helper",
    "category": "file",
    "shortDescription": "Spot duplicate files before cleanup.",
    "processorKey": "duplicateFinder",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "file"
  },
  {
    "slug": "file-info-viewer",
    "title": "File Info Viewer",
    "category": "file",
    "shortDescription": "Inspect file type, size, and metadata.",
    "processorKey": "fileInfo",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": true,
    "icon": "file"
  },
  {
    "slug": "document-page-counter",
    "title": "Document Page Counter",
    "category": "file",
    "shortDescription": "Count pages in supported documents.",
    "processorKey": "pageCounter",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "file"
  },
  {
    "slug": "filename-slugifier",
    "title": "Filename Slugifier",
    "category": "file",
    "shortDescription": "Convert filenames into safe slugs.",
    "processorKey": "filenameSlugifier",
    "inputType": "file",
    "outputType": "file",
    "processingType": "client",
    "pro": false,
    "featureFlags": [],
    "featured": false,
    "icon": "file"
  }
];
